language: python
python:
- '2.7'
- '3.6'
before_install:
- pip install pytest
- pip install six
- pip install coveralls
- pip install pytest-cov
- pip install mkdocs
- mkdocs gh-pages
- python setup.py develop
script:
- py.test --cov-report=term --cov=cli tests
after_success:
- coveralls
env:
  global:
    - GITHUB_REPO: "NCBI-Hackathons/Master_gff3_parser"
    - secure: iAXpdi/03vaMpjSSW9UrL7uDQZ6kw8CPntnzl11jhaCVjcg0ei4FV0lpqMTUAnQxzEDFc+f+OO0PYpF6SNkzofyfp+pL0uN7iCZgJwh0yNaz1E5biiddlv0wdhGcKXI2vtVYE+ysNkEduSUIy7RrSJ3lqS2+XxxVeOOmzPeyFWB8oXOgyMgut5biMQxEXcdYSKLPURBxOykKZ/83HxMEVX6ou2ABejSB2dlNiRVuVghFi9nN+OhQXtn8SMQFs4S3Jgnrop3xrlaVu5RGMMNQQUSErZ2MGwU70ztPGl1R5ZZK44PyHHus3Wg2HuXMwo6Ahggzq7PO/ZGdwURI+w0kbBVxwr9PBdX53b4jnHyNrFZhjXxeCX3m4a6qFlxKGy/mO2P0h1cycpci93ysAcq6ytYlsG5InXfMSqZPhjcTA4kzRQeSYewZSBCllRlXSFIxVvRk7xeWDN3SMwhngqfNoQtrM+shSbxSzW3J2p0d72dfVsvXuV0IB8BlYTu2UsYMAvhIttRGdK+lkGblkCgxnqm3MNUhGdcLu58c5bpBP68L31XzTp/ZUkw1FEJj4Lbw2f40FJhuBK57g1OOAcXBk0KQ0uzMZlAqP+zHfcQLssRsmxogEeNIwHvgpRSegYRKfrufwWgXF0nAuiJbxVIUk0OnKQSayE+LaAOuFoMoiDo=