site_name: GFF3-Parser
theme: readthedocs
pages:
  - Home: index.md
repo_url: https://github.com/NCBI-Hackathons/Master_gff3_parser
site_favicon: favicon.png
markdown_extensions:
    - codehilite
    - toc:
        permalink: True
    - fenced_code
    - sane_lists

markdown_extensions:
    - admonition: